# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_mpimpichpython3.6
    - CONFIG=osx_mpimpichpython3.7
    - CONFIG=osx_mpinompipython3.6
    - CONFIG=osx_mpinompipython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "FI0dAKERgj9qgOrVLkpBQEzdAVF1bia5DYzGEpAOFEWOeD9y5tp6dDGsqSHnu4WI+gNzmk+U10xFKGeEDCfaO0f7z0s9dSkEgU2cNpZKyfUWHc/a2k/HN0ymPLY7+wYkC6VqlUiLMmHq7A7ZQh0UC44eqKP+s4uCZAOBsyh6ACmYYG0ETpj2Gd7bJdHO35+Ob2naFmDi3m88G1sjIjT1s+CNXnnFI61jJU5gz37eN/VIQIzPz1nb2u6mkYiF9Dw4EnlYJXw8fA77diqJnNKYzbpv9RqsaItbRfeXLyTxtvVbim1Msj4k1bwZKJMp03vNMjnhLA5ORv8WIFSJtna5z+AGNh6ORFFgwhP17BVU4EMYtxg1AHwNAo0ten86aacrIm3cD2LCe9sZhQ6kEKyuFUo0R/eP5p7ljNX69hNXudi7qOovzuMPIe5NjsZN9vQIOmiDwcg1CcApWSX3ZObL1+CbmlGUx4A9vegB6VpnPnwpsSOBc+xvlESr+PZ/J4puXdNL55u8Lv5xfGBy+l0+Zyn3iQQ5hZ/dYkJx9J20e9y2vJl/0XLAwKLbj9VijxpiButc9vE7pJsh5TFI4nmuvJ44v9lyj5xNBTHMXjYHd7f0EJDOWAW5s6jYa9gMYz7CCmG5GgJ+lZBWI5/W8rYc3MCLTlsJEbAkHT5ljuQZAJE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2 conda-build
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  -  conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml